#if !canImport(ObjectiveC)
import XCTest

extension KSSWebConstructorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KSSWebConstructorTests = [
        ("testObjectWillCompile", testObjectWillCompile),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(KSSWebConstructorTests.__allTests__KSSWebConstructorTests),
    ]
}
#endif
