AUTHOR := Klassen Software Solutions
AUTHOR_URL := https://www.kss.cc/

include BuildSystem/swift/common.mk

check: Tests/LinuxMain.swift

TEST_SOURCES := $(wildcard Tests/KSSFoundationTests/*.swift Tests/KSSTestTests/*.swift)

Tests/LinuxMain.swift: $(TEST_SOURCES)
	swift test --generate-linuxmain
	echo "// auto-generated by the build system. do not edit" > $@
	echo "" >> $@
	echo "import XCTest" >> $@
	echo "import KSSFoundationTests" >> $@
	echo "import KSSTestTests" >> $@
	echo "" >> $@
	echo "var tests = [XCTestCaseEntry]()" >> $@
	echo "tests += KSSFoundationTests.__allTests()" >> $@
	echo "tests += KSSTestTests.__allTests()" >> $@
	echo "" >> $@
	echo "XCTMain(tests)" >> $@
