AUTHOR := Klassen Software Solutions
AUTHOR_URL := https://www.kss.cc/

include BuildSystem/swift/common.mk

check: Tests/LinuxMain.swift

TEST_SOURCES := $(wildcard Tests/KSSCocoaTests/*.swift Tests/KSSWebTests/*.swift)

Tests/LinuxMain.swift: $(TEST_SOURCES)
	swift test --generate-linuxmain
	echo "// auto-generated by the build system. do not edit" > $@
	echo "" >> $@
	echo "import XCTest" >> $@
	echo "import KSSCocoaTests" >> $@
	echo "import KSSWebTests" >> $@
	echo "" >> $@
	echo "var tests = [XCTestCaseEntry]()" >> $@
	echo "tests += KSSCocoaTests.__allTests()" >> $@
	echo "tests += KSSWebTests.__allTests()" >> $@
	echo "" >> $@
	echo "XCTMain(tests)" >> $@
