// auto-generated by the build system. do not edit

import XCTest
import KSSCocoaTests
import KSSWebTests

var tests = [XCTestCaseEntry]()
tests += KSSCocoaTests.__allTests()
tests += KSSWebTests.__allTests()

XCTMain(tests)
