// auto-generated by the build system. do not edit

import XCTest
import KSSFoundationTests
import KSSTestTests

var tests = [XCTestCaseEntry]()
tests += KSSFoundationTests.__allTests()
tests += KSSTestTests.__allTests()

XCTMain(tests)
